=== mohamedatawfik/schemaflow/misc/sprayflame/nanoparticle_synthesis_conditions.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "nanoparticle_synthesis_conditions",
  "title": "Synthesis Conditions for Nanoparticle Spray Flame Reactor",
  "description": "This dataset captures the experimental conditions for the synthesis of nanoparticles in a spray flame reactor.",
  "type": "object",
  "properties": {
    "FileTypeIdentifier": {
      "title": "FileTypeIdentifier",
      "description": "To allow crawlers to identify JSON files",
      "type": "string",
      "default": "This is a EMPI-RF metadata File. Do not change this for crawler identification",
      "enum": [
        "This is a EMPI-RF metadata File. Do not change this for crawler identification"
      ]
    },
        "Identifier": {
      "title": "Identifier",
      "description": "Unique identifier for the dataset",
      "type": "string"
    },
    "SampleID": {
      "title": "SampleID",
      "description": "Unique identifier for the analyzed sample",
      "type": "string",
      "default": "FexOy-0001-BFR"
    },
    "Creator": {
      "title": "Creator",
      "description": "The name of the primary researcher",
      "type": "string"
    },
    "ORCID": {
      "title": "ORCID",
      "description": "ID of the primary researcher",
      "type": "string"
    },
    "Date": {
      "title": "Date",
      "description": "The date when the experiment started in ISO 8601",
      "type": "string",
      "default": "2025-06-08"
    },
    "Time": {
      "title": "Time",
      "description": "Time when the synthesis started in ISO 8601-1:2019",
      "type": "string"
    },
    "ReactorType": {
      "title": "ReactorType",
      "description": "Type of reactor used (e.g., spray flame reactor)",
      "type": "string",
      "default": "Spray Flame Reactor"
    },
    "PrecursorSolution": {
      "title": "PrecursorSolution",
      "description": "Chemical composition of the precursor solution (e.g., metal salts, solvents)",
      "type": "string"
    },
    "PrecursorConcentration": {
      "title": "PrecursorConcentration",
      "description": "Concentration of the precursor in the solution in mol/L",
      "type": "number"
    },
    "SprayFlowRate": {
      "title": "SprayFlowRate",
      "description": "Flow rate of the precursor spray in mL/min",
      "type": "number"
    },
    "CarrierGas": {
      "title": "CarrierGas",
      "description": "Type of carrier gas used (e.g., nitrogen, air, argon)",
      "type": "string",
      "enum": [
        "nitrogen",
        "air",
        "argon",
        "helium"
      ]
    },
    "CarrierGasFlowRate": {
      "title": "CarrierGasFlowRate",
      "description": "Flow rate of the carrier gas in L/min",
      "type": "number"
    },
    "FlameTemperature": {
      "title": "FlameTemperature",
      "description": "Temperature of the flame in Â°C",
      "type": "number"
    },
    "CombustionEquivalenceRatio": {
      "title": "CombustionEquivalenceRatio",
      "description": "Equivalence ratio of the combustion process",
      "type": "number"
    },
    "SchemaID": {
      "title": "SchemaID",
      "description": "Unique identifier for the schema",
      "type": "string",
      "enum": [
        "nanoparticle_synthesis_conditions"
      ]
    }
  },
  "required": [
    "Identifier",
    "SampleID",
    "Date",
    "Time",
    "ReactorType",
    "PrecursorSolution",
    "PrecursorConcentration",
    "SprayFlowRate",
    "CarrierGas",
    "CarrierGasFlowRate",
    "FlameTemperature",
    "CombustionEquivalenceRatio",
    "SchemaID",
    "FileTypeIdentifier"
  ]
}

=== mohamedatawfik/schemaflow/misc/sprayflame/runs/Spray-Exp_002_20260203_114543.json
{
  "FileTypeIdentifier": "This is a EMPI-RF metadata File. Do not change this for crawler identification",
  "Identifier": "Spray-Exp_002",
  "SampleID": "FexOy-0001-BFR",
  "Creator": "Max Mustermann",
  "ORCID": "5558-8885-5589-8569",
  "Date": "2026-02-03",
  "Time": "11:45:43",
  "ReactorType": "Spray Flame Reactor 5",
  "PrecursorSolution": "FeNO3",
  "PrecursorConcentration": 1,
  "SprayFlowRate": 1,
  "CarrierGas": "air",
  "CarrierGasFlowRate": 1,
  "FlameTemperature": 1500,
  "CombustionEquivalenceRatio": 0.8,
  "SchemaID": "nanoparticle_synthesis_conditions"
}
